### PR TITLE
fix: unicode filenames on Linux

### PR DESCRIPTION
**Pull request by muja**
This bug caused CJK chars in filename to be stripped out.

for example:

`/media/mydisk/fooにほん.rar`  will result in `/media/mydisk/foo` so the open will fail

due to

```cpp
    std::string AnsiArcName;
    if (r->ArcName!=nullptr)
    {
      AnsiArcName=r->ArcName;
      if (!AreFileApisANSI())
        IntToExt(r->ArcName,AnsiArcName);
    }

    std::wstring ArcName;
    if (r->ArcNameW!=nullptr && *r->ArcNameW!=0)
      ArcName=r->ArcNameW;
    else
      CharToWide(AnsiArcName,ArcName);

    Data->Cmd.AddArcName(ArcName);
    Data->Cmd.Overwrite=OVERWRITE_ALL;
    Data->Cmd.VersionControl=1;

    Data->Cmd.Callback=r->Callback;
    Data->Cmd.UserData=r->UserData;

    // Open shared mode is added by request of dll users, who need to
    // browse and unpack archives while downloading.
    Data->Cmd.OpenShared = true;
    if (!Data->Arc.Open(ArcName,FMF_OPENSHARED))
    {
      r->OpenResult=ERAR_EOPEN;
      delete Data;
      return NULL;
    }
```

in `Data->Arc.Open` it will do `WideToChar` which cause the CJK bytes got lost.

but if it calls `CharToWide` first (when `ArcNameW` is nullptr), when it does the reverse, it gets the right filename back.

### CODE REVIEW

**Comment by muja** [comment]
@ttys3 this is a copy of your PR #49 with an added test. Do you mind having a look at this regression? It seems the solution is not universal, not sure how much sense it makes to pursue this

**Comment by ttys3** [comment]
in this way, users of unrar.rs will get better DX and no need to call c method `setlocale`  anymore.
and this issue https://github.com/muja/unrar.rs/issues/44 should been resolved too.

It took me hours to debugging this issue. 

But I think the core reason is that the unrar code from rarlab, has bug while dealing with `ArcNameW` field.
but it does not have bug with  `ArcName` field.

I think we are good to merge this.

**Comment by muja** [comment]
Are you able to see the GitHub checks?
Windows is failing checks: 

```
     Running `D:\a\unrar.rs\unrar.rs\target\debug\deps\utf8-ad60e6114b4a8687.exe`

running 2 tests
test unicode_file ... FAILED
test unicode_list ... ok

failures:

---- unicode_file stdout ----
thread 'unicode_file' panicked at tests\utf8.rs:12:84:
called `Result::unwrap()` on an `Err` value: EOpen@Open (Could not open archive)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ttys3** [comment]
@muja  thanks for the second fixup.

Just checked the code:

https://github.com/muja/unrar.rs/blob/e9c3101e412a472783c4f44ac4defcf98a0b35b3/unrar_sys/vendor/unrar/file.cpp#L47-L154

so, rarlab code will do `WideToChar`  and and use it for the `open` operation.

but for Windows, it does not goes to the `CharToWide` logic due to macro def

for Linux and macOS: it calls CharToWide first (when ArcNameW is nullptr), when it does the reverse, it gets the right filename back.

**Comment by ttys3** [comment]
so here is the thing:

for Windows, it is OK to set and use `ArcNameW` field only
for Windows, it is OK to set and use `ArcName` field only

for macOS, it seems that any one of the above logic works fine.

**Comment by ttys3** [comment]
so here is the thing:

for Windows, it is OK to set and use `ArcNameW` field only
for Linux, it is OK to set and use `ArcName` field only

for macOS, it seems that any one of the above logic works fine.

**Comment by muja** [comment]
Thanks for the investigation. I changed the implementation only for `target_os = "linux"` because the rest worked fine.

**Comment by ttys3** [comment]
just found anothing issue while I'm debugging the windows code in a real windows matchine.

the noew rarlab code has a strange unicode in the comment, which cause msvc compile failed under some machines:

image


I'll create another PR

**Comment by ttys3** [comment]
> just found anothing issue while I'm debugging the windows code in a real windows matchine.

PR created https://github.com/muja/unrar.rs/pull/57

**Pull request merged**
